export const OVERLAY_WINDOW_WIDTH_COMPACT = 340;
export const OVERLAY_WINDOW_WIDTH_EXPANDED = 340;

export const OVERLAY_WINDOW_HEIGHT_COMPACT = 148;
export const OVERLAY_WINDOW_HEIGHT_EXPANDED = 148;

export const OVERLAY_WINDOW_SHOW_DURATION_MS = 400;
export const OVERLAY_WINDOW_HIDE_DURATION_MS = 300;
export const OVERLAY_WINDOW_ANIMATION_DURATION_MS = 150;
export const OVERLAY_WINDOW_SPRING_DAMPING = 18;
export const OVERLAY_WINDOW_SPRING_STIFFNESS = 220;
export const OVERLAY_WINDOW_SPRING_MASS = 1;
export const OVERLAY_WINDOW_SPRING_REST_DISPLACEMENT = 0.5;
export const OVERLAY_WINDOW_SPRING_REST_SPEED = 0.5;

export const OVERLAY_WINDOW_MAX_BLUR_RADIUS = 4;
export const OVERLAY_WINDOW_INITIAL_SCALE = 0.9;

export const OVERLAY_WINDOW_ROOT_PADDING_TOP = 22;
export const OVERLAY_WINDOW_ROOT_PADDING_BOTTOM = 36;

export const OVERLAY_WINDOW_TOP_MARGIN = 48;
export const OVERLAY_WINDOW_HORIZONTAL_MARGIN = 0;
export const OVERLAY_WINDOW_BOTTOM_MARGIN = 0;

export const OVERLAY_CONTENT_SPRING_DAMPING = 18;
export const OVERLAY_CONTENT_SPRING_STIFFNESS = 260;
export const OVERLAY_CONTENT_SPRING_MASS = 1;
export const OVERLAY_CONTENT_SPRING_REST_DISPLACEMENT = 0.01;
export const OVERLAY_CONTENT_SPRING_REST_SPEED = 0.01;
